# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
# Alpine needs build tools for some packages
RUN apk add --no-cache python3 make g++
# Use npm to install
RUN npm install

# Copy source and build
COPY . .
RUN npm run build

# Runtime stage
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and deps
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Default command
CMD ["node", "dist/index.js"]
